# Generated by Django 5.1.2 on 2024-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_created_at_product_user_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
