# Generated by Django 5.1.2 on 2024-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mobile",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
